[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    knolleary/PubSubClient
    miguelbalboa/MFRC522 @ ^1.4.11
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library 
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit BMP280 Library @ ^2.6.8